on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      -
        name: Build extension
        run: npm run build-ext
      - 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "web-ext-artifacts/track_scraper-*.zip"
          omitBody: true
          token: ${{ secrets.GHCR_TOKEN }}